---
title: "essay"
format: html
editor: visual
---

```{r}
if (!require("pacman")) install.packages("pacman")
pacman::p_load(tidyverse, dplyr, readr, sp, raster, sf, here, tmap)

```

# Pour les années récentes (type de données = PG)

```{r}
departments = st_read("/Users/HP/Dropbox/MarketPower_Agri/RPGData/departements-2019-shp/contours-geographiques-tres-simplifies-des-departements-2019.shp")
rpg_map = st_read("/Users/HP/Dropbox/MarketPower_Agri/RPGData/RPG_Corse_2022/PARCELLES_GRAPHIQUES.shp")
```

```{r}
rpg_map <- rpg_map %>% 
  mutate(
    AREA_PARC = st_area(geometry) #To have it in m²
  )
sum(rpg_map$Area_parcels)
sum(rpg__map$SURF_PARC)

rpg_map_small <- rpg_map %>% # Take only 10% of all parcels randomly to work on a random smaller subsample
  slice_sample(n = round(0.1*length(rpg_map$ID_PARCEL)))
departments_rgf93 <- st_transform(departments, crs = st_crs(rpg_map))
rpg_joined <- st_join(rpg_map, departments_rgf93)

rpg_joined_dep <- rpg_joined %>%
  group_by(insee_dep) %>% #First: construct a variable that for each parcel gives the surface of the agricultural area of the department in which it is located
  mutate(Surf_Agri_Dep = sum(SURF_PARC), # Surface of all agricultural parcels in the department
         N_Parcels      = n()
  ) %>% # Number of parcels in the department
  ungroup()
table(rpg_joined_dep$Surf_Agri_Dep) # Just to check the results
table(rpg_joined_dep$N_Parcels)

rpg_culture_bydep <- rpg_joined_dep %>% # Object that contain descriptive statistics
  group_by(insee_dep, CODE_GROUP) %>% # Aggregate by culturer
  summarise(SURF_km2 = sum(SURF_PARC, na.rm = T),# Surface of parcels dedicated to each culture in each department
            SURF_perc = sum(SURF_PARC, na.rm = T) / Surf_Agri_Dep[1], # Percentage in the total agricultural area of the department 
            n_parcels  = n(),
            perc_parcels = n_parcels / N_Parcels[1])
```

# Pour les année IA

```{r}
rpg_map <- rpg_map %>% 
  mutate(
    AREA_PARC = st_area(geometry) #To have it in m²
  )
sum(rpg_map$Area_parcels)
sum(rpg_map$SURF_PARC)

rpg_map_small <- rpg_map %>% # Take only 10% of all parcels randomly to work on a random smaller subsample
  slice_sample(n = round(0.1*length(rpg_map$NUM_ILOT)))
departments_rgf93 <- st_transform(departments, crs = st_crs(rpg_map))
rpg_joined <- st_join(rpg_map, departments_rgf93)

rpg_joined_dep <- rpg_joined %>%
  group_by(insee_dep) %>% #First: construct a variable that for each parcel gives the surface of the agricultural area of the department in which it is located
  mutate(Surf_Agri_Dep = sum(SURF_PARC), # Surface of all agricultural parcels in the department
         N_Parcels      = n()
  ) %>% # Number of parcels in the department
  ungroup()
table(rpg_joined_dep$Surf_Agri_Dep) # Just to check the results
table(rpg_joined_dep$N_Parcels)

rpg_culture_bydep <- rpg_joined_dep %>% # Object that contain descriptive statistics
  group_by(insee_dep, CODE_GROUP) %>% # Aggregate by culturer
  summarise(SURF_km2 = sum(SURF_PARC, na.rm = T),# Surface of parcels dedicated to each culture in each department
            SURF_perc = sum(SURF_PARC, na.rm = T) / Surf_Agri_Dep[1], # Percentage in the total agricultural area of the department 
            n_parcels  = n(),
            perc_parcels = n_parcels / N_Parcels[1])
```
